name: Save

on:
  schedule:
    - cron: "0 0 * * 6,2"
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  save:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run save script
        run: bash save.sh

      - name: Commit & Push
        run: |-
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name  "${{ secrets.GIT_NAME  }}"
          git fetch --unshallow origin
          git add list
          git commit -m 'Update list'
          git push origin main
